apiVersion: batch/v1
kind: Job
metadata:
  name: add-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ['expr','3','+','2']
      restartPolicy: Never
