apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/volume/nginx
  #awsElasticBlockStore:
  #  volumeID: <volume-id>
  #  fsType: ext4
