apiVersion: v1
data:
  DB_HOST: sql322.mycompany.com
  DB_NAME: SQL3322
  DB_PORT: "3306"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-18T10:05:26Z"
  name: cm-3392845
  namespace: default
