apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tails
  name: tails
spec:
  containers:
  - image: busybox
    name: tails
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
